const WSP='59895167187';
let productos=[],texto='',cat='todas';
const $=s=>document.querySelector(s);
const lista=$('#lista'),buscar=$('#buscar'),categoria=$('#categoria'),panel=$('#panel'),contador=$('#contador'),items=$('#items'),total=$('#total');
function n(v){return parseFloat(String(v||'0').replace(/[^0-9.,-]/g,'').replace(',','.'))||0}
function plata(v){return '$ '+Number(v||0).toLocaleString('es-UY')}
function stock(p){const s=Number.isFinite(Number(p.cantidad))?Number(p.cantidad):(Number(p.stock)||0);return s>0?s:0}
function imagenesDe(p){const arr=Array.isArray(p?.imagenes)?p.imagenes.filter(Boolean):[];if(p?.imagen&&!arr.includes(p.imagen))arr.unshift(p.imagen);return [...new Set(arr)]}
function cart(){try{return JSON.parse(sessionStorage.getItem('carrito_catalogo')||'[]')}catch{return[]}}
function save(c){sessionStorage.setItem('carrito_catalogo',JSON.stringify(c));renderCart()}
function getSel(id){const el=document.getElementById(id);return el?el.value:''}
function cantidadEnCarrito(productId){return cart().filter(x=>String(x.id)===String(productId)).reduce((s,x)=>s+x.cantidad,0)}
function cambiarImagen(id,src){const img=document.getElementById('img-'+id);if(img)img.src=src}
function add(id){const p=productos.find(x=>String(x.id)===String(id));if(!p)return;const disponible=stock(p);if(disponible<=0){alert('Producto sin stock disponible.');return}if(cantidadEnCarrito(id)>=disponible){alert('No hay más cantidad disponible para este producto.');return}const color=getSel('color-'+id);const talle=getSel('talle-'+id);if(Array.isArray(p.colores)&&p.colores.length&&!color){alert('Elegí un color.');return}if(Array.isArray(p.talles)&&p.talles.length&&!talle){alert('Elegí un talle.');return}const variante=[color?'Color: '+color:'',talle?'Talle: '+talle:''].filter(Boolean).join(' · ');const cartId=[p.id,color,talle].join('|');const c=cart();const f=c.find(x=>x.cartId===cartId);const img=imagenesDe(p)[0]||'';if(f)f.cantidad++;else c.push({cartId,id:p.id,codigo:p.codigo,nombre:p.nombre,precio:p.precio,imagen:img,color,talle,variante,cantidad:1});save(c);openCart()}
function qty(cartId,d){const c=cart();const item=c.find(x=>x.cartId===cartId);if(!item)return;const p=productos.find(x=>String(x.id)===String(item.id));const disponible=p?stock(p):999999;if(d>0&&cantidadEnCarrito(item.id)>=disponible){alert('No hay más cantidad disponible para este producto.');return}const nuevo=c.map(x=>x.cartId===cartId?{...x,cantidad:x.cantidad+d}:x).filter(x=>x.cantidad>0);save(nuevo)}
function openCart(){panel.classList.add('open')}function closeCart(){panel.classList.remove('open')}
function renderCart(){const c=cart();contador.textContent=c.reduce((s,x)=>s+x.cantidad,0);total.textContent=plata(c.reduce((s,x)=>s+n(x.precio)*x.cantidad,0));items.innerHTML=c.length?c.map(x=>`<div class="item"><img src="${x.imagen||''}" alt="${x.nombre}"><div><b>${x.codigo?`[${x.codigo}] `:''}${x.nombre}</b><div>${x.precio}</div>${x.variante?`<small>${x.variante}</small>`:''}<div class="qty"><button onclick="qty('${x.cartId}',-1)">-</button><span>${x.cantidad}</span><button onclick="qty('${x.cartId}',1)">+</button></div></div><button onclick="qty('${x.cartId}',-999)">×</button></div>`).join(''):'<p>El carrito está vacío.</p>'}
function val(id){const el=$(id);return el?el.value.trim():''}
function msg(){const c=cart();const nombre=val('#clienteNombre'),tel=val('#clienteTelefono'),coment=val('#clienteComentario');let texto='Hola Tu estilo, quiero consultar por estos productos:\n\n';if(c.length){texto+=c.map(x=>`- ${x.codigo?`[${x.codigo}] `:''}${x.nombre}${x.variante?' · '+x.variante:''} x${x.cantidad} (${x.precio})`).join('\n');texto+='\n\nTotal aproximado: '+total.textContent}else texto+='Todavía no agregué productos al carrito.';texto+='\n\nDatos del cliente:';texto+='\nNombre: '+(nombre||'No indicado');texto+='\nTeléfono: '+(tel||'No indicado');if(coment)texto+='\nComentario: '+coment;texto+='\n\nHorario de atención: lunes a sábado de 09 a 19 hs.';return encodeURIComponent(texto)}
function wsp(){window.open(`https://wa.me/${WSP}?text=${msg()}`,'_blank')}
function cats(){const cs=[...new Set(productos.map(x=>x.categoria).filter(Boolean))].sort();categoria.innerHTML='<option value="todas">Todas las categorías</option>'+cs.map(c=>`<option>${c}</option>`).join('')}
function filtrar(){return productos.filter(x=>(x.disponible!==false)&&stock(x)>0&&(`${x.codigo||''} ${x.nombre||''} ${x.descripcion||''} ${x.categoria||''} ${(x.colores||[]).join(' ')} ${(x.talles||[]).join(' ')}`.toLowerCase().includes(texto.toLowerCase()))&&(cat==='todas'||x.categoria===cat))}
function thumbs(id,imgs){return imgs.length>1?`<div class="thumbs">${imgs.map(src=>`<button type="button" onclick="cambiarImagen('${id}','${src}')"><img src="${src}" alt="miniatura"></button>`).join('')}</div>`:''}
function render(){const arr=filtrar();lista.innerHTML=arr.map(p=>{const colores=Array.isArray(p.colores)?p.colores:[];const talles=Array.isArray(p.talles)?p.talles:[];const disponible=stock(p);const imgs=imagenesDe(p);const portada=imgs[0]||'';return `<article class="card"><img id="img-${p.id}" src="${portada}" alt="${p.nombre}">${thumbs(p.id,imgs)}<div class="card-body"><span class="cat">${p.categoria||'Sin categoría'}${p.codigo?' · '+p.codigo:''}</span><h3>${p.nombre}</h3><p>${p.descripcion||''}</p><small>Disponible: ${disponible}</small><div class="variantes">${colores.length?`<select id="color-${p.id}"><option value="">Elegir color</option>${colores.map(v=>`<option value="${v}">${v}</option>`).join('')}</select>`:''}${talles.length?`<select id="talle-${p.id}"><option value="">Elegir talle</option>${talles.map(v=>`<option value="${v}">${v}</option>`).join('')}</select>`:''}</div><span class="precio">${p.precio||'$ 0'}</span><button class="primary" onclick="add('${p.id}')">Agregar al carrito</button></div></article>`}).join('')||'<p>No hay productos para mostrar.</p>'}
async function init(){try{const r=await fetch('productos.json?v='+Date.now());const d=await r.json();productos=Array.isArray(d.productos)?d.productos:[]}catch{productos=[]}cats();render();renderCart()}
buscar.oninput=e=>{texto=e.target.value;render()};categoria.onchange=e=>{cat=e.target.value;render()};$('#btnCarrito').onclick=openCart;$('#cerrar').onclick=closeCart;$('#vaciar').onclick=()=>save([]);$('#whatsapp').onclick=wsp;panel.onclick=e=>{if(e.target===panel)closeCart()};init();
window.cambiarImagen=cambiarImagen;