const WSP='59895167187';
let productos=[],texto='',cat='todas';
const $=s=>document.querySelector(s);
const lista=$('#lista'),buscar=$('#buscar'),categoria=$('#categoria'),panel=$('#panel'),contador=$('#contador'),items=$('#items'),total=$('#total');
function n(v){return parseFloat(String(v||'0').replace(/[^0-9.,-]/g,'').replace(',','.'))||0}
function plata(v){return '$ '+Number(v||0).toLocaleString('es-UY')}
function cart(){try{return JSON.parse(sessionStorage.getItem('carrito_catalogo')||'[]')}catch{return[]}}
function save(c){sessionStorage.setItem('carrito_catalogo',JSON.stringify(c));renderCart()}
function add(id){const p=productos.find(x=>String(x.id)===String(id));if(!p)return;const c=cart();const f=c.find(x=>String(x.id)===String(id));if(f)f.cantidad++;else c.push({id:p.id,codigo:p.codigo,nombre:p.nombre,precio:p.precio,imagen:p.imagen,cantidad:1});save(c);openCart()}
function qty(id,d){const c=cart().map(x=>String(x.id)===String(id)?{...x,cantidad:x.cantidad+d}:x).filter(x=>x.cantidad>0);save(c)}
function openCart(){panel.classList.add('open')}function closeCart(){panel.classList.remove('open')}
function renderCart(){const c=cart();contador.textContent=c.reduce((s,x)=>s+x.cantidad,0);total.textContent=plata(c.reduce((s,x)=>s+n(x.precio)*x.cantidad,0));items.innerHTML=c.length?c.map(x=>`<div class="item"><img src="${x.imagen||''}" alt="${x.nombre}"><div><b>${x.codigo?`[${x.codigo}] `:''}${x.nombre}</b><div>${x.precio}</div><div class="qty"><button onclick="qty('${x.id}',-1)">-</button><span>${x.cantidad}</span><button onclick="qty('${x.id}',1)">+</button></div></div><button onclick="qty('${x.id}',-999)">×</button></div>`).join(''):'<p>El carrito está vacío.</p>'}
function val(id){const el=$(id);return el?el.value.trim():''}
function msg(){const c=cart();const nombre=val('#clienteNombre'),tel=val('#clienteTelefono'),coment=val('#clienteComentario');let texto='Hola Tu estilo, quiero consultar por estos productos:\n\n';if(c.length){texto+=c.map(x=>`- ${x.codigo?`[${x.codigo}] `:''}${x.nombre} x${x.cantidad} (${x.precio})`).join('\n');texto+='\n\nTotal aproximado: '+total.textContent}else texto+='Todavía no agregué productos al carrito.';texto+='\n\nDatos del cliente:';texto+='\nNombre: '+(nombre||'No indicado');texto+='\nTeléfono: '+(tel||'No indicado');if(coment)texto+='\nComentario: '+coment;texto+='\n\nHorario de atención: lunes a sábado de 09 a 19 hs.';return encodeURIComponent(texto)}
function wsp(){window.open(`https://wa.me/${WSP}?text=${msg()}`,'_blank')}
function cats(){const cs=[...new Set(productos.map(x=>x.categoria).filter(Boolean))].sort();categoria.innerHTML='<option value="todas">Todas las categorías</option>'+cs.map(c=>`<option>${c}</option>`).join('')}
function filtrar(){return productos.filter(x=>(x.disponible!==false)&&(`${x.codigo||''} ${x.nombre||''} ${x.descripcion||''} ${x.categoria||''}`.toLowerCase().includes(texto.toLowerCase()))&&(cat==='todas'||x.categoria===cat))}
function render(){const arr=filtrar();lista.innerHTML=arr.map(p=>`<article class="card"><img src="${p.imagen||''}" alt="${p.nombre}"><div class="card-body"><span class="cat">${p.categoria||'Sin categoría'}${p.codigo?' · '+p.codigo:''}</span><h3>${p.nombre}</h3><p>${p.descripcion||''}</p><span class="precio">${p.precio||'$ 0'}</span><button class="primary" onclick="add('${p.id}')">Agregar al carrito</button></div></article>`).join('')||'<p>No hay productos para mostrar.</p>'}
async function init(){try{const r=await fetch('productos.json?v='+Date.now());const d=await r.json();productos=Array.isArray(d.productos)?d.productos:[]}catch{productos=[]}cats();render();renderCart()}
buscar.oninput=e=>{texto=e.target.value;render()};categoria.onchange=e=>{cat=e.target.value;render()};$('#btnCarrito').onclick=openCart;$('#cerrar').onclick=closeCart;$('#vaciar').onclick=()=>save([]);$('#whatsapp').onclick=wsp;panel.onclick=e=>{if(e.target===panel)closeCart()};init();