const PATH='productos.json';let productos=[],sha=null,conf=null;const $=s=>document.querySelector(s);const st=m=>$('#estado').textContent=m;
function cfg(){const c={owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim()};if(!c.owner||!c.repo||!c.branch||!c.token)throw Error('Faltan datos de conexión.');conf=c;sessionStorage.setItem('adm_cfg',JSON.stringify({owner:c.owner,repo:c.repo,branch:c.branch}));sessionStorage.setItem('adm_token',c.token);return c}
function loadCfg(){try{const c=JSON.parse(sessionStorage.getItem('adm_cfg')||'{}');$('#owner').value=c.owner||'leodek';$('#repo').value=c.repo||'catalogo-productos';$('#branch').value=c.branch||'main';$('#token').value=sessionStorage.getItem('adm_token')||''}catch{}}
function slug(t){return String(t||'producto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,70)||'producto'}
function normCodigo(v){return String(v||'').trim().toUpperCase()}
function ref(p){return normCodigo(p?.codigo)||String(p?.id||'')}
function b64(s){let bin='';new TextEncoder().encode(s).forEach(x=>bin+=String.fromCharCode(x));return btoa(bin)}
function from64(s){const bin=atob(String(s).replace(/\n/g,''));return new TextDecoder().decode(Uint8Array.from(bin,c=>c.charCodeAt(0)))}
function file64(f){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f)})}
async function gh(path,opt={}){const c=conf||cfg();const r=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${path}`,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Error GitHub '+r.status);return d}
async function get(path){const c=conf||cfg();return gh(path+'?ref='+encodeURIComponent(c.branch),{method:'GET'})}
async function put(path,content,msg,fileSha=null){const c=conf||cfg();const body={message:msg,content,branch:c.branch};if(fileSha)body.sha=fileSha;return gh(path,{method:'PUT',body:JSON.stringify(body)})}
async function delFile(path,msg){const f=await get(path);const c=conf||cfg();return gh(path,{method:'DELETE',body:JSON.stringify({message:msg,sha:f.sha,branch:c.branch})})}
async function cargar(){try{cfg();const f=await get(PATH);sha=f.sha;const d=JSON.parse(from64(f.content));productos=Array.isArray(d.productos)?d.productos:[];render();st('Productos cargados: '+productos.length)}catch(e){if(String(e.message).includes('Not Found')){productos=[];sha=null;render();st('No existe productos.json. Se creará al guardar.')}else st('Error: '+e.message)}}
async function subirFoto(nombre,codigo){const f=$('#foto').files[0];if(!f)return null;const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const base=slug(codigo+'-'+nombre);const path=`img/productos/${Date.now()}-${base}.${ext}`;await put(path,await file64(f),'Subo foto '+path);return path}
async function borrarFotoSiCorresponde(path,codigoActual){if(!path||!path.startsWith('img/productos/'))return 'Sin foto para borrar.';const usada=productos.some(x=>ref(x)!==codigoActual&&x.imagen===path);if(usada)return 'Foto conservada: otro producto la usa.';try{await delFile(path,'Elimino foto '+path);return 'Foto eliminada de GitHub.'}catch(e){return 'No pude borrar la foto: '+e.message}}
async function guardarJson(){const r=await put(PATH,b64(JSON.stringify({productos},null,2)),'Actualizo productos',sha);sha=r.content.sha}
function validarCodigoUnico(codigo,codigoOriginal){const nuevo=normCodigo(codigo);const anterior=normCodigo(codigoOriginal);const repetido=productos.some(p=>ref(p)===nuevo&&ref(p)!==anterior);if(repetido)throw Error('Ya existe un producto con el código '+nuevo+'. No se pueden repetir códigos.')}
function datos(old,img,codigoOriginal){const codigo=normCodigo($('#codigo').value);return{id:codigo,codigo,nombre:$('#nombre').value.trim(),categoria:$('#cat').value.trim(),precio:$('#precio').value.trim(),descripcion:$('#desc').value.trim(),imagen:img||old?.imagen||'',disponible:$('#disp').value==='true',codigo_anterior:codigoOriginal&&codigoOriginal!==codigo?codigoOriginal:undefined}}
async function guardar(e){e.preventDefault();try{cfg();const codigo=normCodigo($('#codigo').value);if(!codigo)throw Error('El código es obligatorio.');if(!$('#nombre').value.trim())throw Error('El nombre es obligatorio.');const codigoOriginal=normCodigo($('#pid').value);validarCodigoUnico(codigo,codigoOriginal);st('Guardando...');const old=codigoOriginal?productos.find(x=>ref(x)===codigoOriginal):null;const img=await subirFoto($('#nombre').value,codigo);let msgFoto='';if(old&&img&&old.imagen&&old.imagen!==img){msgFoto=await borrarFotoSiCorresponde(old.imagen,codigoOriginal)}const p=datos(old,img,codigoOriginal);productos=old?productos.map(x=>ref(x)===codigoOriginal?p:x):[...productos,p];await guardarJson();limpiar();render();st('Producto guardado con referencia '+codigo+'. '+msgFoto+' Puede demorar unos minutos en verse publicado.')}catch(err){st('Error: '+err.message)}}
function editar(codigo){const key=normCodigo(codigo);const p=productos.find(x=>ref(x)===key);if(!p)return;$('#pid').value=ref(p);$('#codigo').value=p.codigo||ref(p);$('#nombre').value=p.nombre||'';$('#cat').value=p.categoria||'';$('#precio').value=p.precio||'';$('#desc').value=p.descripcion||'';$('#disp').value=String(p.disponible!==false);$('#tituloForm').textContent='Editar producto';scrollTo({top:0,behavior:'smooth'})}
async function borrar(codigo){const key=normCodigo(codigo);const p=productos.find(x=>ref(x)===key);if(!p||!confirm('¿Eliminar únicamente el producto ['+key+'] '+(p.nombre||'')+'? También se intentará borrar solo su foto si no la usa otro producto.'))return;try{cfg();const img=p.imagen;productos=productos.filter(x=>ref(x)!==key);await guardarJson();const fotoMsg=await borrarFotoSiCorresponde(img,key);render();st('Producto ['+key+'] eliminado. '+fotoMsg)}catch(e){st('Error: '+e.message)}}
function limpiar(){$('#form').reset();$('#pid').value='';$('#disp').value='true';$('#tituloForm').textContent='Nuevo producto'}
function listaFiltrada(){const nom=($('#filtroNombre')?.value||'').toLowerCase();const cod=($('#filtroCodigo')?.value||'').toLowerCase();return productos.filter(p=>(!nom||String(p.nombre||'').toLowerCase().includes(nom))&&(!cod||ref(p).toLowerCase().includes(cod)))}
function render(){const box=$('#productos');const arr=listaFiltrada();box.innerHTML=arr.length?arr.map(p=>{const key=ref(p);return `<div class="row"><img src="../${p.imagen||''}"><div><b>[${key}] ${p.nombre||''}</b><div>${p.categoria||''} · ${p.precio||''}</div><small>${p.disponible===false?'No disponible':'Disponible'}</small></div><div class="acciones"><button onclick="editar('${key}')">Editar</button><button onclick="borrar('${key}')">Eliminar</button></div></div>`}).join(''):'<p>No hay productos para mostrar.</p>'}
$('#guardarConfig').onclick=()=>{try{cfg();st('Conexión guardada para esta sesión.')}catch(e){st(e.message)}};$('#cargar').onclick=cargar;$('#form').onsubmit=guardar;$('#limpiar').onclick=limpiar;$('#filtroNombre')?.addEventListener('input',render);$('#filtroCodigo')?.addEventListener('input',render);loadCfg();render();