const PATH='productos.json';let productos=[],sha=null,conf=null;const $=s=>document.querySelector(s),st=m=>$('#estado').textContent=m;
function cfg(){let c={owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim()};if(!c.owner||!c.repo||!c.branch||!c.token)throw Error('Faltan datos de conexión.');conf=c;sessionStorage.setItem('adm_cfg',JSON.stringify({owner:c.owner,repo:c.repo,branch:c.branch}));sessionStorage.setItem('adm_token',c.token);return c}
function loadCfg(){try{let c=JSON.parse(sessionStorage.getItem('adm_cfg')||'{}');$('#owner').value=c.owner||'leodek';$('#repo').value=c.repo||'catalogo-productos';$('#branch').value=c.branch||'main';$('#token').value=sessionStorage.getItem('adm_token')||''}catch{}}
function norm(v){return String(v||'').trim().toUpperCase()}function ref(p){return norm(p?.codigo)||String(p?.id||'')}function slug(t){return String(t||'producto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,70)||'producto'}
function b64(s){let b='';new TextEncoder().encode(s).forEach(x=>b+=String.fromCharCode(x));return btoa(b)}function de64(s){let b=atob(String(s).replace(/\n/g,''));return new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0)))}
function file64(f){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(String(r.result).split(',')[1]);r.onerror=rej;r.readAsDataURL(f)})}
async function gh(path,opt={}){let c=conf||cfg(),r=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${path}`,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28',...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Error GitHub '+r.status);return d}
async function get(path){let c=conf||cfg();return gh(path+'?ref='+encodeURIComponent(c.branch),{method:'GET'})}
async function put(path,content,msg,s=null){let c=conf||cfg(),body={message:msg,content,branch:c.branch};if(s)body.sha=s;return gh(path,{method:'PUT',body:JSON.stringify(body)})}
async function cargarBase(){try{let f=await get(PATH),d=JSON.parse(de64(f.content));sha=f.sha;productos=Array.isArray(d.productos)?d.productos:[]}catch(e){if(String(e.message).includes('Not Found')){sha=null;productos=[]}else throw e}}
async function cargar(){try{cfg();await cargarBase();render();st('Productos cargados: '+productos.length)}catch(e){st('Error: '+e.message)}}
async function subirFoto(nombre,codigo){let f=$('#foto').files[0];if(!f)return null;let ext=(f.name.split('.').pop()||'jpg').toLowerCase(),path=`img/productos/${Date.now()}-${slug(codigo+'-'+nombre)}.${ext}`;await put(path,await file64(f),'Subo foto '+path,null);return path}
async function borrarFoto(path,codigoActual){if(!path||!path.startsWith('img/productos/'))return 'Sin foto para borrar.';if(productos.some(x=>ref(x)!==codigoActual&&x.imagen===path))return 'Foto conservada: otro producto la usa.';try{let f=await get(path);if(!f.sha)return 'No encontré SHA de la foto.';let c=conf||cfg();await gh(path,{method:'DELETE',body:JSON.stringify({message:'Elimino foto '+path,sha:f.sha,branch:c.branch})});return 'Foto eliminada de GitHub.'}catch(e){return 'No pude borrar la foto: '+e.message}}
async function guardarJson(){let r=await put(PATH,b64(JSON.stringify({productos},null,2)),'Actualizo productos',sha);sha=r.content.sha}
function datos(old,img,codOrig){let codigo=norm($('#codigo').value);return{id:codigo,codigo,nombre:$('#nombre').value.trim(),categoria:$('#cat').value.trim(),precio:$('#precio').value.trim(),descripcion:$('#desc').value.trim(),imagen:img||old?.imagen||'',disponible:$('#disp').value==='true',codigo_anterior:codOrig&&codOrig!==codigo?codOrig:undefined}}
async function guardar(e){e.preventDefault();try{cfg();let codigo=norm($('#codigo').value),codOrig=norm($('#pid').value);if(!codigo)throw Error('El código es obligatorio.');if(!$('#nombre').value.trim())throw Error('El nombre es obligatorio.');st('Guardando...');await cargarBase();let old=codOrig?productos.find(x=>ref(x)===codOrig):null;if(productos.some(p=>ref(p)===codigo&&ref(p)!==codOrig))throw Error('Ya existe un producto con el código '+codigo+'.');let img=await subirFoto($('#nombre').value,codigo),msg='';if(old&&img&&old.imagen&&old.imagen!==img)msg=await borrarFoto(old.imagen,codOrig);let p=datos(old,img,codOrig);productos=old?productos.map(x=>ref(x)===codOrig?p:x):[...productos,p];await guardarJson();limpiar();render();st('Producto guardado con referencia '+codigo+'. '+msg)}catch(err){st('Error: '+err.message)}}
function editar(codigo){let k=norm(codigo),p=productos.find(x=>ref(x)===k);if(!p)return;$('#pid').value=ref(p);$('#codigo').value=p.codigo||ref(p);$('#nombre').value=p.nombre||'';$('#cat').value=p.categoria||'';$('#precio').value=p.precio||'';$('#desc').value=p.descripcion||'';$('#disp').value=String(p.disponible!==false);$('#tituloForm').textContent='Editar producto';scrollTo({top:0,behavior:'smooth'})}
async function borrar(codigo){let key=norm(codigo);try{cfg();await cargarBase();let p=productos.find(x=>ref(x)===key);if(!p)throw Error('El producto ya no existe.');if(!confirm('¿Eliminar únicamente el producto ['+key+'] '+(p.nombre||'')+'?'))return;let img=p.imagen;productos=productos.filter(x=>ref(x)!==key);await guardarJson();let m=await borrarFoto(img,key);render();st('Producto ['+key+'] eliminado. '+m)}catch(e){st('Error: '+e.message)}}
function limpiar(){$('#form').reset();$('#pid').value='';$('#disp').value='true';$('#tituloForm').textContent='Nuevo producto'}
function filtrados(){let n=($('#filtroNombre')?.value||'').toLowerCase(),c=($('#filtroCodigo')?.value||'').toLowerCase();return productos.filter(p=>(!n||String(p.nombre||'').toLowerCase().includes(n))&&(!c||ref(p).toLowerCase().includes(c)))}
function render(){let box=$('#productos'),arr=filtrados();box.innerHTML=arr.length?arr.map(p=>{let k=ref(p);return `<div class="row"><img src="../${p.imagen||''}"><div><b>[${k}] ${p.nombre||''}</b><div>${p.categoria||''} · ${p.precio||''}</div><small>${p.disponible===false?'No disponible':'Disponible'}</small></div><div class="acciones"><button onclick="editar('${k}')">Editar</button><button onclick="borrar('${k}')">Eliminar</button></div></div>`}).join(''):'<p>No hay productos para mostrar.</p>'}
$('#guardarConfig').onclick=()=>{try{cfg();st('Conexión guardada para esta sesión.')}catch(e){st(e.message)}};$('#cargar').onclick=cargar;$('#form').onsubmit=guardar;$('#limpiar').onclick=limpiar;$('#filtroNombre')?.addEventListener('input',render);$('#filtroCodigo')?.addEventListener('input',render);loadCfg();render();