const PATH='productos.json';
let productos=[];
let fileSha=null;
let conf=null;
const $=s=>document.querySelector(s);
const st=m=>$('#estado').textContent=m;
function norm(v){return String(v||'').trim().toUpperCase()}
function key(p){return norm(p?.codigo)||String(p?.id||'')}
function slug(t){return String(t||'producto').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'').slice(0,80)||'producto'}
function cfg(){const c={owner:$('#owner').value.trim(),repo:$('#repo').value.trim(),branch:$('#branch').value.trim()||'main',token:$('#token').value.trim()};if(!c.owner||!c.repo||!c.branch||!c.token)throw Error('Faltan datos de conexión.');conf=c;sessionStorage.setItem('adm_cfg',JSON.stringify({owner:c.owner,repo:c.repo,branch:c.branch}));sessionStorage.setItem('adm_token',c.token);return c}
function loadCfg(){try{const c=JSON.parse(sessionStorage.getItem('adm_cfg')||'{}');$('#owner').value=c.owner||'leodek';$('#repo').value=c.repo||'catalogo-productos';$('#branch').value=c.branch||'main';$('#token').value=sessionStorage.getItem('adm_token')||''}catch{}}
function enc(text){let b='';new TextEncoder().encode(text).forEach(x=>b+=String.fromCharCode(x));return btoa(b)}
function dec(b64){const bin=atob(String(b64||'').replace(/\n/g,''));return new TextDecoder().decode(Uint8Array.from(bin,c=>c.charCodeAt(0)))}
function file64(file){return new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(String(r.result).split(',')[1]);r.onerror=fail;r.readAsDataURL(file)})}
async function gh(path,opt={}){const c=conf||cfg();const r=await fetch(`https://api.github.com/repos/${c.owner}/${c.repo}/contents/${path}`,{cache:'no-store',...opt,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${c.token}`,'X-GitHub-Api-Version':'2022-11-28','Cache-Control':'no-cache',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||('Error GitHub '+r.status));return d}
async function getFile(path){const c=conf||cfg();return gh(path+'?ref='+encodeURIComponent(c.branch)+'&t='+Date.now(),{method:'GET'})}
async function putFile(path,content,message,sha=null){const c=conf||cfg();const body={message,content,branch:c.branch};if(sha)body.sha=sha;return gh(path,{method:'PUT',body:JSON.stringify(body)})}
async function deleteFile(path,message){const f=await getFile(path);if(!f.sha)throw Error('No se encontró SHA para borrar '+path);const c=conf||cfg();return gh(path,{method:'DELETE',body:JSON.stringify({message,sha:f.sha,branch:c.branch})})}
async function cargarProductos(){try{const f=await getFile(PATH);fileSha=f.sha;const data=JSON.parse(dec(f.content));productos=Array.isArray(data.productos)?data.productos:[]}catch(e){if(String(e.message).includes('Not Found')){productos=[];fileSha=null}else throw e}}
async function guardarProductos(){const fresh=await getFile(PATH).catch(e=>null);if(fresh&&fresh.sha)fileSha=fresh.sha;const content=enc(JSON.stringify({productos},null,2));try{const r=await putFile(PATH,content,'Actualizo productos',fileSha);fileSha=r.content.sha}catch(e){if(String(e.message).includes('does not match')||String(e.message).includes('sha')){const f=await getFile(PATH);fileSha=f.sha;const r=await putFile(PATH,content,'Actualizo productos',fileSha);fileSha=r.content.sha}else throw e}}
async function subirFoto(codigo,nombre){const file=$('#foto').files[0];if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`img/productos/${Date.now()}-${slug(codigo+'-'+nombre)}.${ext}`;await putFile(path,await file64(file),'Subo foto '+path,null);return path}
async function borrarFoto(path,codigoActual){if(!path||!path.startsWith('img/productos/'))return 'Sin foto para borrar.';if(productos.some(p=>key(p)!==codigoActual&&p.imagen===path))return 'Foto conservada porque otro producto la usa.';try{await deleteFile(path,'Elimino foto '+path);return 'Foto eliminada.'}catch(e){return 'No se pudo borrar la foto: '+e.message}}
function validarCodigo(codigo,original){if(!codigo)throw Error('El código es obligatorio.');if(productos.some(p=>key(p)===codigo&&key(p)!==original))throw Error('Ya existe un producto con el código '+codigo+'.')}
function productoDesdeForm(old,img,original){const codigo=norm($('#codigo').value);return{id:codigo,codigo,nombre:$('#nombre').value.trim(),categoria:$('#cat').value.trim(),precio:$('#precio').value.trim(),descripcion:$('#desc').value.trim(),imagen:img||old?.imagen||'',disponible:$('#disp').value==='true',codigo_anterior:original&&original!==codigo?original:undefined}}
async function cargar(){try{cfg();await cargarProductos();render();st('Productos cargados: '+productos.length)}catch(e){st('Error: '+e.message)}}
async function guardar(e){e.preventDefault();try{cfg();await cargarProductos();const codigo=norm($('#codigo').value);const original=norm($('#pid').value);if(!$('#nombre').value.trim())throw Error('El nombre es obligatorio.');validarCodigo(codigo,original);st('Guardando...');const old=original?productos.find(p=>key(p)===original):null;const img=await subirFoto(codigo,$('#nombre').value);let msg='';if(old&&img&&old.imagen&&old.imagen!==img)msg=await borrarFoto(old.imagen,original);const prod=productoDesdeForm(old,img,original);productos=old?productos.map(p=>key(p)===original?prod:p):[...productos,prod];await guardarProductos();limpiar();render();st('Producto guardado: '+codigo+'. '+msg)}catch(e){st('Error: '+e.message)}}
function editar(codigo){const k=norm(codigo);const p=productos.find(x=>key(x)===k);if(!p)return;$('#pid').value=key(p);$('#codigo').value=p.codigo||key(p);$('#nombre').value=p.nombre||'';$('#cat').value=p.categoria||'';$('#precio').value=p.precio||'';$('#desc').value=p.descripcion||'';$('#disp').value=String(p.disponible!==false);$('#tituloForm').textContent='Editar producto';scrollTo({top:0,behavior:'smooth'})}
async function borrar(codigo){try{cfg();await cargarProductos();const k=norm(codigo);const p=productos.find(x=>key(x)===k);if(!p)throw Error('El producto ya no existe.');if(!confirm('¿Eliminar ['+k+'] '+(p.nombre||'')+'?'))return;const img=p.imagen;productos=productos.filter(x=>key(x)!==k);await guardarProductos();const msg=await borrarFoto(img,k);render();st('Producto eliminado: '+k+'. '+msg)}catch(e){st('Error: '+e.message)}}
function limpiar(){$('#form').reset();$('#pid').value='';$('#disp').value='true';$('#tituloForm').textContent='Nuevo producto'}
function filtrados(){const n=($('#filtroNombre')?.value||'').toLowerCase();const c=($('#filtroCodigo')?.value||'').toLowerCase();return productos.filter(p=>(!n||String(p.nombre||'').toLowerCase().includes(n))&&(!c||key(p).toLowerCase().includes(c)))}
function render(){const box=$('#productos');const arr=filtrados();box.innerHTML=arr.length?arr.map(p=>{const k=key(p);return `<div class="row"><img src="../${p.imagen||''}"><div><b>[${k}] ${p.nombre||''}</b><div>${p.categoria||''} · ${p.precio||''}</div><small>${p.disponible===false?'No disponible':'Disponible'}</small></div><div class="acciones"><button onclick="editar('${k}')">Editar</button><button onclick="borrar('${k}')">Eliminar</button></div></div>`}).join(''):'<p>No hay productos cargados.</p>'}
$('#guardarConfig').onclick=()=>{try{cfg();st('Conexión guardada.')}catch(e){st(e.message)}};
$('#cargar').onclick=cargar;$('#form').onsubmit=guardar;$('#limpiar').onclick=limpiar;$('#filtroNombre')?.addEventListener('input',render);$('#filtroCodigo')?.addEventListener('input',render);
loadCfg();if($('#token').value.trim()){cargar()}else{render()}
window.editar=editar;window.borrar=borrar;